/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FigurasGeometricas;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaFiguras extends javax.swing.JFrame {

    /**
     * Creates new form VentanFiguras
     */
    public VentanaFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtArea_Cir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtPer_Cir = new javax.swing.JTextField();
        TxtRadio_Cir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtLado_Cuad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtArea_Cuad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtPer_Cuad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtBase_Rec = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtAlt_Rec = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtArea_Rec = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtPer_Rec = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtLado_Rmb = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtDM_Rmb = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Txtdm_Rmb = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxtArea_Rmb = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtPer_Rmb = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxtBM_Tp = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Txtbm_Tp = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxtAlt_Tp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        TxtDBA_Tp = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TxtArea_Tp = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TxtPer_Tp = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TxtBase_TR = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        TxtAlt_TR = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        TxtHip_TR = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        TxtArea_TR = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        TxtPer_TR = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        TxtTipo_TR = new javax.swing.JTextField();
        Calc_Cir = new javax.swing.JButton();
        Limp_Cir = new javax.swing.JButton();
        Calc_Cuad = new javax.swing.JButton();
        Limp_Cuad = new javax.swing.JButton();
        Calc_Rec = new javax.swing.JButton();
        Limp_Rec = new javax.swing.JButton();
        Calc_Rmb = new javax.swing.JButton();
        Limp_Rmb = new javax.swing.JButton();
        Limp_Tp = new javax.swing.JButton();
        Calc_Tp = new javax.swing.JButton();
        Calc_TR = new javax.swing.JButton();
        Limp_TR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Circulo:");

        jLabel2.setText("Radio");

        jLabel3.setText("Area");

        jLabel4.setText("Perimetro");

        jLabel5.setText("Cuadrado:");

        jLabel6.setText("Lado");

        jLabel7.setText("Area");

        jLabel8.setText("Perimetro");

        jLabel9.setText("Rectangulo:");

        jLabel10.setText("Base");

        jLabel11.setText("Altura");

        jLabel12.setText("Area");

        jLabel13.setText("Perimetro");

        jLabel14.setText("Rombo:");

        jLabel15.setText("Lado");

        jLabel16.setText("Diagonal Mayor");

        jLabel17.setText("Diagonal Menor");

        jLabel18.setText("Area");

        jLabel19.setText("Perimetro");

        jLabel20.setText("Trapecio:");

        jLabel21.setText("Base Mayor");

        jLabel22.setText("Base menor");

        jLabel23.setText("Altura");

        jLabel24.setText("Distancia Base-Altura");

        jLabel25.setText("Area");

        jLabel26.setText("Perimetro");

        jLabel27.setText("Triangulo Rectangulo:");

        jLabel28.setText("Base");

        jLabel29.setText("Altura");

        jLabel30.setText("Hipotenusa");

        jLabel31.setText("Area");

        jLabel32.setText("Perimetro");

        jLabel33.setText("Tipo");

        Calc_Cir.setText("Calcular");
        Calc_Cir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_CirActionPerformed(evt);
            }
        });

        Limp_Cir.setText("Limpiar");
        Limp_Cir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limp_CirActionPerformed(evt);
            }
        });

        Calc_Cuad.setText("Calcular");
        Calc_Cuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_CuadActionPerformed(evt);
            }
        });

        Limp_Cuad.setText("Limpiar");
        Limp_Cuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limp_CuadActionPerformed(evt);
            }
        });

        Calc_Rec.setText("Calcular");
        Calc_Rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_RecActionPerformed(evt);
            }
        });

        Limp_Rec.setText("Limpiar");
        Limp_Rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limp_RecActionPerformed(evt);
            }
        });

        Calc_Rmb.setText("Calcular");
        Calc_Rmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_RmbActionPerformed(evt);
            }
        });

        Limp_Rmb.setText("Limpiar");
        Limp_Rmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limp_RmbActionPerformed(evt);
            }
        });

        Limp_Tp.setText("Limpiar");
        Limp_Tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limp_TpActionPerformed(evt);
            }
        });

        Calc_Tp.setText("Calcular");
        Calc_Tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_TpActionPerformed(evt);
            }
        });

        Calc_TR.setText("Calcular");
        Calc_TR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_TRActionPerformed(evt);
            }
        });

        Limp_TR.setText("Limpiar");
        Limp_TR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limp_TRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBM_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(Txtbm_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(TxtAlt_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(TxtDBA_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(TxtArea_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(TxtPer_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Calc_Tp)
                        .addGap(18, 18, 18)
                        .addComponent(Limp_Tp)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtLado_Rmb))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtBase_Rec))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtLado_Cuad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TxtArea_Cuad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TxtAlt_Rec)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TxtPer_Cuad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TxtArea_Rec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel13)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TxtPer_Rec, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtDM_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(Txtdm_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtArea_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtPer_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtRadio_Cir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtArea_Cir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtPer_Cir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Calc_Cuad)
                                    .addComponent(Calc_Rec)
                                    .addComponent(Calc_Rmb)
                                    .addComponent(Calc_Cir)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtBase_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtAlt_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtHip_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel31)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtArea_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtPer_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel33)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtTipo_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115)
                                        .addComponent(Calc_TR)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Limp_Cir)
                                .addComponent(Limp_Cuad)
                                .addComponent(Limp_Rec)
                                .addComponent(Limp_Rmb))
                            .addComponent(Limp_TR))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtRadio_Cir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(TxtArea_Cir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(TxtPer_Cir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limp_Cir))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtLado_Cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TxtArea_Cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(TxtPer_Cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limp_Cuad))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TxtBase_Rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(TxtAlt_Rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(TxtArea_Rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(TxtPer_Rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limp_Rec))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TxtLado_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(TxtDM_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(Txtdm_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(TxtArea_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(TxtPer_Rmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limp_Rmb)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Calc_Cir)
                        .addGap(52, 52, 52)
                        .addComponent(Calc_Cuad)
                        .addGap(52, 52, 52)
                        .addComponent(Calc_Rec)
                        .addGap(52, 52, 52)
                        .addComponent(Calc_Rmb)))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TxtBM_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Txtbm_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(TxtAlt_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(TxtDBA_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(TxtArea_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(TxtPer_Tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limp_Tp)
                    .addComponent(Calc_Tp))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(TxtBase_TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(TxtAlt_TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(TxtHip_TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(TxtArea_TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(TxtPer_TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(TxtTipo_TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calc_TR)
                    .addComponent(Limp_TR))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Calc_CirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_CirActionPerformed
        // TODO add your handling code here:
        try{
            double radio = Double.parseDouble(TxtRadio_Cir.getText());
            double area = Circulo.calcularArea(radio);
            double perimetro = Circulo.calcularPerimetro(radio);
            
            TxtArea_Cir.setText(String.valueOf(area));
            TxtPer_Cir.setText(String.valueOf(perimetro));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
    }//GEN-LAST:event_Calc_CirActionPerformed

    private void Calc_CuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_CuadActionPerformed
        // TODO add your handling code here:
        try{
            double lado = Double.parseDouble(TxtLado_Cuad.getText());
            double area = Cuadrado.calcularArea(lado);
            double perimetro = Cuadrado.calcularPerimetro(lado);
            
            TxtArea_Cuad.setText(String.valueOf(area));
            TxtPer_Cuad.setText(String.valueOf(perimetro));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
    }//GEN-LAST:event_Calc_CuadActionPerformed

    private void Calc_RecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_RecActionPerformed
        // TODO add your handling code here:
        try{
            double base = Double.parseDouble(TxtBase_Rec.getText());
            double altura = Double.parseDouble(TxtAlt_Rec.getText());
            
            double area = Rectangulo.calcularArea(base, altura);
            double perimetro = Rectangulo.calcularPerimetro(base, altura);
            
            TxtArea_Rec.setText(String.valueOf(area));
            TxtPer_Rec.setText(String.valueOf(perimetro));
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
    }//GEN-LAST:event_Calc_RecActionPerformed

    private void Calc_RmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_RmbActionPerformed
        // TODO add your handling code here:
        try{
            double lado = Double.parseDouble(TxtLado_Rmb.getText());
            double DM = Double.parseDouble(TxtDM_Rmb.getText());
            double dm = Double.parseDouble(Txtdm_Rmb.getText());
            
            double area = Rombo.calcularArea(DM, dm);
            double perimetro = Rombo.calcularPerimetro(lado);
            
            TxtArea_Rmb.setText(String.valueOf(area));
            TxtPer_Rmb.setText(String.valueOf(perimetro));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
    }//GEN-LAST:event_Calc_RmbActionPerformed

    private void Calc_TpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_TpActionPerformed
        // TODO add your handling code here:
        try{
            double BM = Double.parseDouble(TxtBM_Tp.getText());
            double bm = Double.parseDouble(Txtbm_Tp.getText());
            double altura = Double.parseDouble(TxtAlt_Tp.getText());
            double DBA = Double.parseDouble(TxtDBA_Tp.getText());
            
            double area = Trapecio.calcularArea(BM, bm, altura);
            double hipo = Trapecio.calcularHipotenusa(altura, DBA);
            double perimetro = Trapecio.calcularPerimetro(BM, bm, hipo);
            
            TxtArea_Tp.setText(String.valueOf(area));
            TxtPer_Tp.setText(String.valueOf(perimetro));
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
    }//GEN-LAST:event_Calc_TpActionPerformed

    private void Calc_TRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_TRActionPerformed
        // TODO add your handling code here:
        try{
            double base = Double.parseDouble(TxtBase_TR.getText());
            double altura = Double.parseDouble(TxtAlt_TR.getText());
            
            double hipotenusa = TrianguloRectangulo.calcularHipotenusa(base, altura);
            double area = TrianguloRectangulo.calcularArea(base, altura);
            double perimetro = TrianguloRectangulo.calcularPerimetro(base, altura, hipotenusa);
            
            String tipo = TrianguloRectangulo.tipoDeTriangulo(base, altura, hipotenusa);
            
            TxtHip_TR.setText(String.valueOf(hipotenusa));
            TxtArea_TR.setText(String.valueOf(area));
            TxtPer_TR.setText(String.valueOf(perimetro));
            TxtTipo_TR.setText(tipo);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
    }//GEN-LAST:event_Calc_TRActionPerformed

    private void Limp_CirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limp_CirActionPerformed
        // TODO add your handling code here:
        TxtRadio_Cir.setText("");
        TxtArea_Cir.setText("");
        TxtPer_Cir.setText("");
    }//GEN-LAST:event_Limp_CirActionPerformed

    private void Limp_CuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limp_CuadActionPerformed
        // TODO add your handling code here:
        TxtLado_Cuad.setText("");
        TxtArea_Cuad.setText("");
        TxtPer_Cuad.setText("");
    }//GEN-LAST:event_Limp_CuadActionPerformed

    private void Limp_RecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limp_RecActionPerformed
        // TODO add your handling code here:
        TxtBase_Rec.setText("");
        TxtAlt_Rec.setText("");
        TxtArea_Rec.setText("");
        TxtPer_Rec.setText("");
        
    }//GEN-LAST:event_Limp_RecActionPerformed

    private void Limp_RmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limp_RmbActionPerformed
        // TODO add your handling code here:
        TxtLado_Rmb.setText("");
        TxtDM_Rmb.setText("");
        Txtdm_Rmb.setText("");
        TxtArea_Rmb.setText("");
        TxtPer_Rmb.setText("");
        
    }//GEN-LAST:event_Limp_RmbActionPerformed

    private void Limp_TpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limp_TpActionPerformed
        // TODO add your handling code here:
        TxtBM_Tp.setText("");
        Txtbm_Tp.setText("");
        TxtAlt_Tp.setText("");
        TxtDBA_Tp.setText("");
        TxtArea_Tp.setText("");
        TxtPer_Tp.setText("");
        
    }//GEN-LAST:event_Limp_TpActionPerformed

    private void Limp_TRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limp_TRActionPerformed
        // TODO add your handling code here:
        TxtBase_TR.setText("");
        TxtAlt_TR.setText("");
        TxtHip_TR.setText("");
        TxtArea_TR.setText("");
        TxtPer_TR.setText("");
        TxtTipo_TR.setText("");
        
    }//GEN-LAST:event_Limp_TRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calc_Cir;
    private javax.swing.JButton Calc_Cuad;
    private javax.swing.JButton Calc_Rec;
    private javax.swing.JButton Calc_Rmb;
    private javax.swing.JButton Calc_TR;
    private javax.swing.JButton Calc_Tp;
    private javax.swing.JButton Limp_Cir;
    private javax.swing.JButton Limp_Cuad;
    private javax.swing.JButton Limp_Rec;
    private javax.swing.JButton Limp_Rmb;
    private javax.swing.JButton Limp_TR;
    private javax.swing.JButton Limp_Tp;
    private javax.swing.JTextField TxtAlt_Rec;
    private javax.swing.JTextField TxtAlt_TR;
    private javax.swing.JTextField TxtAlt_Tp;
    private javax.swing.JTextField TxtArea_Cir;
    private javax.swing.JTextField TxtArea_Cuad;
    private javax.swing.JTextField TxtArea_Rec;
    private javax.swing.JTextField TxtArea_Rmb;
    private javax.swing.JTextField TxtArea_TR;
    private javax.swing.JTextField TxtArea_Tp;
    private javax.swing.JTextField TxtBM_Tp;
    private javax.swing.JTextField TxtBase_Rec;
    private javax.swing.JTextField TxtBase_TR;
    private javax.swing.JTextField TxtDBA_Tp;
    private javax.swing.JTextField TxtDM_Rmb;
    private javax.swing.JTextField TxtHip_TR;
    private javax.swing.JTextField TxtLado_Cuad;
    private javax.swing.JTextField TxtLado_Rmb;
    private javax.swing.JTextField TxtPer_Cir;
    private javax.swing.JTextField TxtPer_Cuad;
    private javax.swing.JTextField TxtPer_Rec;
    private javax.swing.JTextField TxtPer_Rmb;
    private javax.swing.JTextField TxtPer_TR;
    private javax.swing.JTextField TxtPer_Tp;
    private javax.swing.JTextField TxtRadio_Cir;
    private javax.swing.JTextField TxtTipo_TR;
    private javax.swing.JTextField Txtbm_Tp;
    private javax.swing.JTextField Txtdm_Rmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
